name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-docker-image:
    name: build-and-publish-docker-image
    runs-on: ubuntu-latest

    # GHCR への push に必要
    permissions:
      contents: read
      packages: write

    # 同じブランチでの重複ビルドを抑止
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # （任意）マルチアーキでなくても Buildx を明示的に有効化しておくと安定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GHCR にログイン（GITHUB_TOKEN で OK）
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # タグとラベルの自動生成
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # main/master に push → latest/branch、タグ push → vX.Y.Z などを自動付与
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # ビルド＆プッシュ（PR のときは push=false）
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
